import { vi } from 'vitest';
import { AppDatabase } from '../../src/storage/database.js';
import { BridgeService } from '../../src/services/bridge.js';

// Shared harness for BridgeService delivery-path tests: a REAL in-memory
// SQLite database (so the actual SQL statements and migrations are exercised)
// plus vi.fn() fakes for the three I/O collaborators. Every fake resolves to
// a benign success by default; individual tests override just the calls whose
// behavior they probe (e.g. maxClient.readMessages, telegramBot.sendMessage).
//
// Do not edit this file from a test — pass `overrides` to the factories or
// reassign `bridge.<collaborator>.<method>` locally instead.

export function makeFakeMaxClient(overrides = {}) {
  return {
    page: { url: () => 'https://web.max.ru/chats' },
    start: vi.fn(async () => {}),
    stop: vi.fn(async () => {}),
    waitForReady: vi.fn(async () => {}),
    // Default: a healthy signed-in session, so the QR sign-in flow no-ops.
    getSessionState: vi.fn(async () => 'ready'),
    captureLoginQr: vi.fn(async () => null),
    listChats: vi.fn(async () => []),
    selectChat: vi.fn(async () => {}),
    readMessages: vi.fn(async () => []),
    sendText: vi.fn(async () => {}),
    sendFile: vi.fn(async () => {}),
    getLastOutgoingFingerprint: vi.fn(async () => null),
    isTyping: vi.fn(async () => false),
    healthCheck: vi.fn(async () => ({
      browserConnected: true,
      url: 'https://web.max.ru/chats',
      pageTitle: 'MAX',
      chatCount: 1,
      checks: []
    })),
    captureDiagnostics: vi.fn(async () => null),
    ...overrides
  };
}

export function makeFakeTelegramBot(overrides = {}) {
  let nextMessageId = 1000;
  return {
    start: vi.fn(async () => {}),
    stop: vi.fn(() => {}),
    targetChatId: vi.fn(() => -100500),
    createTopic: vi.fn(async () => 7700),
    renameTopic: vi.fn(async () => true),
    sendMessage: vi.fn(async () => ({ message_id: nextMessageId++ })),
    sendText: vi.fn(async () => ({ message_id: nextMessageId++ })),
    sendDocument: vi.fn(async () => ({ message_id: nextMessageId++ })),
    sendPinnedText: vi.fn(async () => ({ message_id: nextMessageId++, pinned: true })),
    onMessage: vi.fn(),
    onChats: vi.fn(),
    onSelectChat: vi.fn(),
    onHistory: vi.fn(),
    onStatus: vi.fn(),
    onSync: vi.fn(),
    onCheck: vi.fn(),
    onDiagnostics: vi.fn(),
    onDeliveries: vi.fn(),
    onMerge: vi.fn(),
    onUnmerge: vi.fn(),
    onLogin: vi.fn(),
    onIdentityDiscovered: vi.fn(),
    startPairing: vi.fn(() => '424242'),
    sendOwnerText: vi.fn(async () => ({ message_id: 9000 })),
    sendOwnerQr: vi.fn(async (png, existingId) => existingId || 9100),
    deleteOwnerMessage: vi.fn(async () => true),
    ...overrides
  };
}

export function makeFakeMediaService(overrides = {}) {
  return {
    // Identity conversions by default: the "converted" file is the input file.
    downloadUrl: vi.fn(async (url, name) => `/tmp/media/${name}.bin`),
    ensureTelegramCompatible: vi.fn(async (filePath) => filePath),
    ensureMaxCompatible: vi.fn(async (filePath) => filePath),
    imageDHash: vi.fn(async () => 'a1b2c3d4e5f60718'),
    fileContentHash: vi.fn(async () => 'f'.repeat(32)),
    framesDirToGif: vi.fn(async (dir) => `${dir}/out.gif`),
    cleanupOlderThan: vi.fn(async () => {}),
    ...overrides
  };
}

// Mirrors the shape of src/config.js with fast test-friendly values.
// `overrides.telegram` is merged one level deep so a test can flip a single
// telegram flag without restating the whole block.
export function makeTestConfig(overrides = {}) {
  const { telegram, ...rest } = overrides;
  return {
    env: 'test',
    logLevel: 'silent',
    telegram: {
      ownerId: 12345,
      relayChatId: -100500,
      useTopics: true,
      autoCreateTopics: true,
      ...telegram
    },
    pollIntervalMs: 5,
    historyLimit: 50,
    maxChatsPerPoll: 4,
    maxPollFailuresBeforeRestart: 3,
    maxDeliveryAttempts: 2,
    startupPrimeExistingMessages: false,
    startupPrimeChatsLimit: 0,
    diagnosticDir: '/tmp/diagnostics-test',
    diagnosticFilesLimit: 4,
    diagnosticRetentionFiles: 10,
    diagnosticRedactText: true,
    mediaDir: '/tmp/media-test',
    sqlitePath: ':memory:',
    ...rest
  };
}

// Builds a BridgeService over a real in-memory database and fake collaborators.
// Returns every piece so tests can assert on the fakes and seed the db.
export function makeBridge({ maxClient, telegramBot, mediaService, config } = {}) {
  const db = new AppDatabase(':memory:');
  const bridge = new BridgeService({
    db,
    maxClient: maxClient || makeFakeMaxClient(),
    telegramBot: telegramBot || makeFakeTelegramBot(),
    mediaService: mediaService || makeFakeMediaService(),
    config: config || makeTestConfig()
  });
  return {
    bridge,
    db,
    maxClient: bridge.maxClient,
    telegramBot: bridge.telegramBot,
    mediaService: bridge.mediaService,
    config: bridge.config
  };
}

// Seeds a MAX chat plus a ready-to-use Telegram route for it, so
// ensureMapping/resolveTelegramMapping take the "existing mapping" fast path.
// topicIntroMessageId is pre-set so ensureTopicIntro does not send a pin.
export function linkChat(db, chatId, {
  title = chatId,
  telegramChatId = -100500,
  telegramThreadId = 77,
  unread = false
} = {}) {
  db.upsertChat({ id: chatId, title, lastSeenAt: Date.now(), metadata: { unread } });
  db.upsertChatMapping({
    maxChatId: chatId,
    telegramChatId,
    telegramThreadId,
    title,
    metadata: { createdBy: 'test', topicIntroMessageId: 1 }
  });
  return db.getChatMapping(chatId);
}

// Minimal MAX-side message row as produced by maxClient.readMessages /
// consumed by forwardMaxMessage and pollMax.
export function maxMessage(id, chatId, {
  type = 'text',
  text = `text of ${id}`,
  mediaUrl = null,
  mediaPath = null,
  sourceMessageId = `fp-${id}|12:00|x`,
  metadata = {}
} = {}) {
  return {
    id,
    chatId,
    direction: 'max_to_tg',
    type,
    text,
    mediaUrl,
    mediaPath,
    sourceMessageId,
    createdAt: Date.now(),
    metadata
  };
}

// Minimal Telegram-side message as produced by the telegramBot adapter /
// consumed by handleTelegramMessage.
export function telegramMessage(id, {
  type = 'text',
  text = `tg text ${id}`,
  mediaPath = null,
  telegramChatId = -100500,
  telegramThreadId = 77,
  metadata = {}
} = {}) {
  return {
    id,
    chatId: null,
    direction: 'tg_to_max',
    type,
    text,
    mediaPath,
    sourceMessageId: String(id).replace(/^tg-/, ''),
    createdAt: Date.now(),
    metadata: { telegramChatId, telegramThreadId, ...metadata }
  };
}
